modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/jaredlll08/Ambient-Environment/issues"
[[mods]] #mandatory
modId="ambientenvironment" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ambient Environment" #mandatory
credits="MC Bedrock edition lol" #optional
authors="Jaredlll08" #optional
updateJSONURL="https://updates.blamejared.com/get?n=AmbientEnvironment&gv=1.16.5"
description='''
Adds more ambiance to the game
'''
displayURL="https://www.curseforge.com/minecraft/mc-mods/ambient-environment"